# Generated by Django 3.2.11 on 2022-01-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20220116_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='original_sentence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='translated_sentence',
            field=models.TextField(blank=True, null=True),
        ),
    ]
